// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlpRv6G0e6bHiUntVCpNKEzZmpzJcnQD8',
    appId: '1:801209522987:web:c9b4a393d066244a28436e',
    messagingSenderId: '801209522987',
    projectId: 'earning-fish-dev',
    authDomain: 'earning-fish-dev.firebaseapp.com',
    storageBucket: 'earning-fish-dev.firebasestorage.app',
    measurementId: 'G-Q85P8VK7GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWp7Tku5gSpZ-WEsoLBnC011GHb069uGA',
    appId: '1:801209522987:android:3a340f4b0c9156a928436e',
    messagingSenderId: '801209522987',
    projectId: 'earning-fish-dev',
    storageBucket: 'earning-fish-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4A5CGrFnHEWoz5ZdXXQLcNKdnRHC_PU',
    appId: '1:801209522987:ios:1026b7a718fdb74f28436e',
    messagingSenderId: '801209522987',
    projectId: 'earning-fish-dev',
    storageBucket: 'earning-fish-dev.firebasestorage.app',
    iosBundleId: 'com.earning.fish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4A5CGrFnHEWoz5ZdXXQLcNKdnRHC_PU',
    appId: '1:801209522987:ios:1026b7a718fdb74f28436e',
    messagingSenderId: '801209522987',
    projectId: 'earning-fish-dev',
    storageBucket: 'earning-fish-dev.firebasestorage.app',
    iosBundleId: 'com.earning.fish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlpRv6G0e6bHiUntVCpNKEzZmpzJcnQD8',
    appId: '1:801209522987:web:3e19cf40aa865ac428436e',
    messagingSenderId: '801209522987',
    projectId: 'earning-fish-dev',
    authDomain: 'earning-fish-dev.firebaseapp.com',
    storageBucket: 'earning-fish-dev.firebasestorage.app',
    measurementId: 'G-G7Q1FT4GBZ',
  );
}
